name: DASH_NYU
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch>=1.9.0
    - torchdiffeq>=0.2.0
    - numpy>=1.19.0
    - matplotlib>=3.3.0
    - tqdm>=4.60.0
    - pandas>=1.3.0
    - configparser
    - adjustText
